name: assistant
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
 
  fluttertoast: ^8.2.1
  email_validator: ^3.0.0
  

 
  
  
    # Updated version
  
  
  sqflite: ^2.0.0+4
  permission_handler: ^10.0.0
 
  
  provider: ^6.0.0
  flutter_datetime_picker: ^1.5.1
  font_awesome_flutter: ^10.1.0
  table_calendar: ^3.1.2
  awesome_notifications: ^0.9.3+1
  
  
 
  share: ^2.0.4
  sqflite_common_ffi: ^2.0.0+4

  google_fonts: ^6.2.1
 
  path_provider: ^2.1.4
  share_plus: ^10.0.0
  shared_preferences: ^2.3.0
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    

 